## Extras Numpy


In [1]:
import numpy as np

Generar Matrices Aleatorias:

    Crea una matriz AA de dimensiones 5×4 con números aleatorios enteros entre 1 y 10.
    Imprime la matriz.

In [12]:
a = 1
b = 10
(b-a)*np.random.rand(5,4)+a

array([[7.59534762, 2.79879184, 4.60964154, 8.28451661],
       [2.32241567, 6.22614723, 2.7004248 , 9.17334733],
       [2.29768767, 7.27951954, 1.43980971, 7.7585271 ],
       [7.87630265, 6.19938252, 1.35365222, 1.84090326],
       [2.0797676 , 5.71085477, 7.47214668, 4.68524662]])

Filtrado de Elementos: 

    Dada la matriz B=np.array([[1,2,3],[4,5,6],[7,8,9]]), crea una nueva matriz que contenga solo los números pares de B.

In [29]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

filtrado_pares = (B % 2 == 0)
numeros_pares = B[filtrado_pares]

print(numeros_pares)


[2 4 6 8]


Suma por Columnas:

    Crea una matriz CC de dimensiones 3×3 con números aleatorios entre 1 y 100.
    Calcula la suma de cada columna.

In [48]:
a = 1
b = 100
matriz_CC = (b-a)*np.random.rand(3,3)+a

suma_columnas = np.sum(matriz_CC, axis=0)

print(matriz_CC)

print(suma_columnas)

[[25.06067012 35.85651286  3.20684702]
 [22.28319622 88.48158345 67.4966262 ]
 [12.07547747 37.72031282 96.04985611]]
[ 59.41934381 162.05840912 166.75332933]


Normalización de una Matriz:

    Dada una matriz DD de dimensiones 4×4 con valores aleatorios entre 0 y 255, normaliza sus valores para que estén en el rango [0, 1].

In [61]:
matriz_DD = np.random.randint(0, 256, size=(4, 4))
matriz_normalizada = matriz_DD / 255.0

print(matriz_normalizada)

[[0.89411765 0.89019608 0.51372549 0.1372549 ]
 [1.         0.72156863 0.02352941 0.28235294]
 [0.74117647 0.70588235 0.60392157 0.30980392]
 [0.07058824 0.76470588 0.37647059 0.1372549 ]]


Diagonal Principal:

    Genera una matriz EE de dimensiones 5×5 con valores aleatorios entre 1 y 50.
    Extrae e imprime la diagonal principal.

Multiplicación de Matrices:

    Crea dos matrices F y G de dimensiones 3×3.
    Calcula e imprime el resultado de F×G.

Promedio de una Matriz:

    Genera una matriz H de dimensiones 4×5 con números aleatorios entre 0 y 100.
    Calcula e imprime el promedio de todos los valores en H.

Trasposición y Adición:

    Crea una matriz I de dimensiones 2×3 con números aleatorios entre 1 y 10.
    Calcula su transposición IT y suma ambas matrices: I+IT. (Nota: IT tendrá dimensiones 3×2, así que tendrás que ajustar las matrices para que se puedan sumar).

Elemento Mayor y su Posición:

    Genera una matriz J de dimensiones 4×4 con valores aleatorios entre 1 y 100.
    Encuentra e imprime el valor más grande de la matriz y su posición (índice de fila e índice de columna).

Reemplazo Condicional:

    Crea una matriz KK de dimensiones 3×3 con números aleatorios entre 0 y 10.
    Reemplaza cualquier número mayor a 5 con el valor 1 y cualquier número menor o igual a 5 con el valor 0.
    Imprime la matriz resultante.

Escribe un programa que seleccione un número al azar entre 1 y 100 y le 
pida al usuario que lo adivine. El programa debe indicar si el número 
introducido por el usuario es más alto o más bajo que el número 
seleccionado al azar, hasta que el usuario adivine correctamente o 
decida abandonar.