# NumPy Ejercicios

#### Importar librería


In [3]:
import numpy as np

#### Crear una array (unidimensional) con 10 ceros

In [4]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Resultado esperado:
```python
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

#### Crear un array (unidimensional) con 10 unos

In [5]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Resultado esperado:
```python
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

#### Crear un array con 10 cincos

In [6]:
np.ones(10, int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Resultado esperado:
```python
array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])
```

#### Crear un array (unidimensional) con los números enteros desde 10 hasta 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Resultado esperado:
```python
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
```

#### Crear un array (unidimensional) con los enteros pares comprendidos entre 10 y 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Resultado esperado:
```python
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```

### Crear una matriz 10x10 con los enteros comprendidos entre 0 y 99

In [10]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### Crear una matriz identidad de orden 3

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Resultado esperado:
```python
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
```

#### Generar un número aleatorio proveniente de una distribución uniforme, entre 0 y 1

In [12]:
np.random.rand(1)


array([0.82674039])

#### Obtener 25 números aleatorios procedentes de una distribución normal estandar

In [13]:
np.random.rand(5,5)

array([[0.13076056, 0.12866267, 0.54003714, 0.90626698, 0.49801136],
       [0.50565498, 0.18039166, 0.40688621, 0.63624349, 0.74909799],
       [0.97298485, 0.67906024, 0.84917275, 0.95563503, 0.92819421],
       [0.34323566, 0.28966589, 0.90689609, 0.27480505, 0.36563508],
       [0.69964318, 0.97272714, 0.87208553, 0.39481769, 0.29285651]])

#### Genera la siguiente matriz:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [14]:
matriz = np.arange(0.01, 1.01, 0.01).reshape(10, 10)

print(matriz)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Crear un vector de 20 valores equidistantes entre 0 y 1

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Resultado esperado:
```python
array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])
```

## Numpy Indexado y filtrado

Dada la siguiente matriz, realice las operaciones pertinentes para obtener la salida que se pide:

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Primer ejercicio**

In [17]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

*Resultado esperado:*


```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```



**Segundo ejercicio**

In [18]:
mat[3,4]

20

*Resultado esperado:*

```
20
```



In [34]:
mat[:3,1:-3]

array([[ 2],
       [ 7],
       [12]])

In [36]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

*Resultado esperado:*

```
array([[ 2],
       [ 7],
       [12]])
```



**Cuarto ejercicio**

In [20]:
mat[4]

array([21, 22, 23, 24, 25])

In [37]:
mat[-1,:]

array([21, 22, 23, 24, 25])

*Resultado esperado:*


```
array([21, 22, 23, 24, 25])
```



**Quinto ejercicio**

In [21]:
mat[[3,4]]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
mat[-2:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

*Resultado esperado:*


```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



### Realice los siguiente cálculos:

#### Obtenga la suma de todos los valores de la matriz

In [22]:
np.sum(mat)

325

*Resultado esperado:*


```python
325
```

#### Calcule la desviación típica de los valores de la matriz

In [23]:
np.std(mat)

7.211102550927978

*Resultado esperado:*


```python
7.211102550927978
```

#### Sume los valores por columnas


In [24]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

*Resultado esperado:*


```python
array([55, 60, 65, 70, 75])
```

## Ejercicio extra (Juego)

### Escribe un programa que seleccione un numero al azar entre 1 y 100 y le pida al usuario que los adivine.
El programa debe indicar si el numero introducido por el usuario es más alto o más bajo que le número seleccionado al azar, hasta que el usuario adivine correctamente o decida abandonar.

In [40]:
import random

numero_azar = random.randint(1, 100)

intentos = 0
adivinado = False

print("Adivine el numero al azar")

while not adivinado:
    intento = input("Escribe tu número o escribe 'salir' para abandonar: ")

    if intento.lower() == 'salir':
        print("El número secreto era", numero_azar)
        break

    try:
        intento = int(intento)
    except ValueError:
        print("Por favor, ingresa un número válido.")
        continue

    intentos += 1

    if intento < numero_azar:
        print("El número secreto es más alto. Intentelo de nuevo.")
    elif intento > numero_azar:
        print("El número secreto es más bajo. Intententelo de nuevo")
    else:
        print(f"Felicidades, has adivinado el número secreto {numero_azar} en {intentos} intentos.")
        adivinado = True


Adivine el numero al azae
El número secreto era 72


## Avanzado

### Obtenga el rango de la siguiente matriz cuadrada:

```python
Z = np.random.uniform(0,1,(10,10))
```

*(Indicaciones: Al ser cuadrada, podemos analizar sus autovalores)*

In [25]:
#Z = np.random.uniform(0,1,(10,10))
#U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
#rank = np.sum(S > 1e-10)
#print(rank)